name: 'Auto Milestone Summary Action'
description: 'Automatically generate and update planning issues based on milestones'
author: 'elliotxx'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
  planning_label:
    description: 'Label to identify planning issues'
    required: false
    default: 'planning'
  categories:
    description: 'JSON array of category labels'
    required: false
    default: '["bug", "documentation", "enhancement"]'

runs:
  using: 'composite'
  steps:
    - name: Checkout action
      uses: actions/checkout@v3
      with:
        repository: elliotxx/auto-milestone-summary-action
        path: .github/actions/auto-milestone-summary-action

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      shell: bash
      working-directory: .github/actions/auto-milestone-summary-action
      run: npm ci

    - name: Build and Run
      shell: bash
      working-directory: .github/actions/auto-milestone-summary-action
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PLANNING_LABEL: ${{ inputs.planning_label }}
        INPUT_CATEGORIES: ${{ inputs.categories }}
      run: |
        npm run build
        node dist/index.js

branding:
  icon: 'clipboard'
  color: 'blue'
