name: 'Community Planning Updater'
description: 'Automatically generate and update planning issues based on GitHub milestones'
author: 'elliotxx'

inputs:
  token:
    description: 'GitHub token'
    required: true
  planning_label:
    description: 'Label for planning issues'
    required: false
    default: 'planning'
  categories:
    description: 'Categories for issues (JSON array of strings)'
    required: false
    default: '["bug", "documentation", "enhancement"]'
  exclude_pr:
    description: 'Whether to exclude pull requests from the summary'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout action
      uses: actions/checkout@v3
      with:
        repository: elliotxx/community-planning-updater
        path: .github/actions/community-planning-updater

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      shell: bash
      working-directory: .github/actions/community-planning-updater
      run: npm ci

    - name: Build and Run
      shell: bash
      working-directory: .github/actions/community-planning-updater
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PLANNING_LABEL: ${{ inputs.planning_label }}
        INPUT_CATEGORIES: ${{ inputs.categories }}
        INPUT_EXCLUDE_PR: ${{ inputs.exclude_pr }}
      run: |
        npm run build
        node dist/index.js

branding:
  icon: 'coffee'
  color: 'yellow_dark'
