name: 'Auto Milestone Summary Action'
description: 'Automatically generate and update planning issues based on milestones'
author: 'elliotxx'
branding:
  icon: 'clipboard'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
  planning_label:
    description: 'Label to identify planning issues'
    required: false
    default: 'planning'
  categories:
    description: 'JSON array of category labels'
    required: false
    default: '["bug", "documentation", "enhancement"]'

runs:
  using: 'node16'
  main: 'dist/index.js'
