name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/index.js
            dist/index.js.map
            dist/sourcemap-register.js
          body: |
            ## Changes
            Please refer to the commit history for detailed changes.

            ## Usage
            ```yaml
            - uses: elliotxx/auto-milestone-summary-action@${{ github.ref_name }}
              with:
                token: \${{ secrets.GITHUB_TOKEN }}
            ```
